### PR TITLE
Create ruRU.lua

### PR DESCRIPTION
**Pull request by dak1ne-4th**

### CODE REVIEW

**Comment by dak1ne-4th** [comment]
ye, u right!
and btw i`ve updated file a bit, but will post it in corret place.

**Comment by melroy999** [comment]
Good! I can see the localization files you have provided on the repository forks--I will add them to the repositories once you have made a new pull requests for them (or I can add them directly, if that is what you prefer).

**Comment by dak1ne-4th** [comment]
pull requests rdy for TRCore and Mech locales.
sry i`m new to githib so now everything in UI is 'clear' for me.

**Comment by melroy999** [comment]
No problem, everyone needs to be given a chance to learn! However, it would seem that you have accidentally made a pull request in your own repository. You are merging your changes to your own master branch (dak1ne-4th:master), instead of mine (melroy999:master).

**Pull request closed without merging**
